name: 🐞 Bug or error report
description: Report an anomaly or unexpected behavior in this repository.
labels: ['Needs: Triage :mag:', 'type:bug-suspected']

body:
- type: markdown
  attributes:
    value: |
      - [x] Bug

      Thank you for reporting a bug! Use the sections below to submit a bug **only** if it's related to samples in this repo. 
      
      - Follow our guidance on [How To Create Good Issues](https://github.com/pnp/sharing-is-caring/wiki/How-to-Create-Good-Issues).
      - All bug reports are welcome - we want to fix them!
      - This repo is maintained by volunteers. Please be courteous and patient. 🙂
      - Remember to include sufficient details and context.
      - If you have multiple questions, suggestions, or bugs, please submit them in separate issues.
      - We accept pull requests. If you know how to fix it - go ahead! If you know how to make it - go ahead! If you're unsure how to do a pull request, consider signing up for a free [Sharing is Caring First-Time Contributor](http://aka.ms/sharing-is-caring#pnp-sic-first-time-contributor) session.

      Please provide the following details about the issue you encountered.  *Issues that do not provide the information requested in this form will be flagged as **incomplete** & automatically closed.*

- type: markdown
  attributes:
    value: |
      Provide a clear & concise description of what the bug is. Please follow our guidance on [How To Create Good Issues](https://github.com/pnp/sharing-is-caring/wiki/How-to-Create-Good-Issues) which explains how to apply formatting, adding references & resources, screenshots, etc. 
      
      **Do not attach ZIP files** of your code or compiled projects - instead, please publish your code to a public GitHub repo & post a link to it.

- type: textarea
  id: what-happened
  attributes:
    label: What is the issue?
    description: Describe the observed behavior
    placeholder: Tell us what you see!
  validations:
    required: true
